### PR TITLE
removed old html-files and updated readme

### PR DESCRIPTION
**Pull request by rcnijzink**

### CODE REVIEW

**Review by schymans — CHANGES_REQUESTED** [review]
I cannot see the updates to README.md.  VOM_Fortran/VOM-docu/html_docu/README.txt was deleted, but the relevant information from there should be migrated to README.md, along with a link to vom.readthedocs.com and the html-files VOM-docu/build/html.

**Comment by rcnijzink** [comment]
Sorry, forgot to add the readme to the commit.... It's all the way at the bottom
I am not sure if most information in the old readme (VOM_Fortran/VOM-docu/html_docu/README.txt) is still relevant, it's about editing the html-files.

**Review by schymans — APPROVED** [review]

**Review by schymans — CHANGES_REQUESTED** [review]
Actually, this part from the old readme.txt in VOM-docu is still relevant:

> The documentation of VOM consists of two pdf files containing equations,
and two directories containing html documentation. 

> The directory Fordocu contains automatically generated documenation
based on comments in the .f90 files. This one is helpful for understanding the
structure of the source code.

Could you add this to  README.md, along with the sentence about the online and offline docu? Maybe even create a new heading `Model documentation`.

Talking of which, is the Fordocu still up to date?

**Comment by schymans** [comment]
I just realised that Fordocu has not been updated for ages. Need to cd into the fordocu folder and run `generate_fordocu.sh`. We could do this in a separate issue and PR.

**Comment by rcnijzink** [comment]
Ok, I added the relevant part to Readme.md. 
I also added the pdf's as a link in the readthedocs.
Ideally, we should add a link to the fordocu part too. I tried to generate it, but generate_fordocu.sh has some hard-coded dependencies. Need to have a better look at it and will make an issue for that part of the documentation.

**Review by schymans — APPROVED** [review]

**Comment by schymans** [comment]
OK, this is great, thanks! I think we can merge and I will open another issue to update Fordocu.

**Pull request merged**
