### PR TITLE
Add inputfolderpath

### PR DESCRIPTION
**Pull request by rcnijzink**
Added in the namelist an option for the input folder and the output folder.

### CODE REVIEW

**Comment by schymans** [comment]
Before merging, could you check VOM-Docu and adapt the instructions to reflect the new way of interacting with the VOM? For example the description in: https://github.com/schymans/VOM/blob/master/VOM_Fortran/VOM-docu/html_docu/HowToRun.html

**Comment by rcnijzink** [comment]
Sorry, keep forgetting this... I made it an issue and will update the docs.

**Comment by schymans** [comment]
OK, thanks. Can you push the updated docu to the same PR, before we merge?

**Comment by rcnijzink** [comment]
Yes, I'll do it on this branch, for this pull request. Almost done... ;)

**Comment by rcnijzink** [comment]
I pushed an updated HowToRun to this branch now. Just let me know if anything is missing ;)

**Review by schymans — APPROVED** [review]
Thanks, that's great!

**Pull request merged**
