### PR TITLE
Add baresoil fraction to namelist for esoil calculation

### PR DESCRIPTION
**Pull request by rcnijzink**
I removed the constants from the equation and put those in the modules-file. The fraction of bare soil is now a parameter in the namelist.

### CODE REVIEW

**Review by schymans — CHANGES_REQUESTED** [review]
The naming is misleading, as it does not have an effect on absorbed shortwave radiation by vegetation. Maybe call it "radiative transmissivity of vegetation cover"? Then it would become clear why it can be set to 0 once we get the relation between LAI and light absorption right.

**Comment by schymans** [comment]
Thanks for doing this, Remko. However, there are two problems. One is a conflict with VOM_Fortran/VOM_test/ref_test/vom_namelist and the other one is that the naming could be misleading, as indicated in my review.

**Comment by rcnijzink** [comment]
I made changes accordingly and called the parameter in the namelist now i_trans_vegcov. I also updated the description in the documentation.

**Review by schymans — CHANGES_REQUESTED** [review]
This makes more sense. Just to make it really clear, I would change "radiative transmissivity of vegetation cover (0-1), i.e. fraction of radiative energy to reach the ground even under a closed canopy" to "fraction of radiative energy reaching soil under full cover (0-1), used only for calculation of soil evaporation."

**Comment by schymans** [comment]
Thanks, last change requested, trying to make clear that this only affects soil evaporation and relates to energy penetrating the canopy in whatever form. Could be downwards emission of longwave radiation from heated canopy, which is currently not modelled at all.

**Comment by rcnijzink** [comment]
Ok, I updated the descriptions!

**Pull request merged**
