### PR TITLE
Topoparam sce

### PR DESCRIPTION
**Pull request by rcnijzink**
I did this already some weeks ago and run it. I don't think there was a pull request already.

### CODE REVIEW

**Comment by schymans** [comment]
This is included in PR #11, right? Should it be closed, then?

**Comment by rcnijzink** [comment]
Just as PR #11, it is a clean PR now. Both pull requests could now be pulled independently.

**Comment by rcnijzink** [comment]
I think we should re-open this one. The changes are not in your master, I don't get it...

**Comment by schymans** [comment]
Could you create a new PR, based on the current master and apply the missing changes? I think this would be the safest way.

**Comment by rcnijzink** [comment]
Yes, we did actually already with https://github.com/schymans/VOM/pull/13
So this one stays closed, sorry for all the confusion...

**Pull request merged**
