### PR TITLE
Update Fordocu

### LINKED ISSUE #49: Update Fordocu-part of the documentation

### PR DESCRIPTION
**Pull request by schymans**
Updates the contents of Fordocu to reflect current code. Closes #49.

### CODE REVIEW

**Review by rcnijzink — COMMENTED** [review]
Hi Stan, I don't see any changes in Fordocu/README.txt and there is no link. Maybe good to add those?

**Comment by schymans** [comment]
Sorry, the link is actually in the script itself: generate_fordocu.sh.
It is not needed by the user, only by the developer to update the docu after changes in the code, this is why I did not include it in the readme. I actually just realised that my PR does not reflect the merged changes in your previous PR, need to verify.

**Comment by schymans** [comment]
OK, the PR is based on the updated master, but the VOM-docu/README.txt had not been removed or updated, which confused me. I removed it now.

**Review by rcnijzink — APPROVED** [review]
So I think is should be fine then, I also managed to run the fordocu. Maybe we could add this to generate_fordocu.sh to make it more general:

```
fordocu_dir=$1
cd ../../VOM-code
perl $fordocu_dir/fordocu.pl -1 -free *.f90 \
```

in this way you have to specify it to the command line.

**Comment by schymans** [comment]
Thanks for the suggestion! I just made the change and tested it.

**Pull request merged**
